# Generated by Django 5.2.2 on 2025-08-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(db_index=True, max_length=64)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('taxable_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('source_file', models.FileField(upload_to='po_uploads/')),
                ('extracted_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['po_number'], name='invoices_pu_po_numb_5aa694_idx'), models.Index(fields=['po_date'], name='invoices_pu_po_date_0926c6_idx'), models.Index(fields=['created_at'], name='invoices_pu_created_8646bc_idx')],
            },
        ),
    ]
