# Generated by Django 5.2.2 on 2025-08-19 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='extracted_json',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tax_total',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='taxable_total',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor_name',
        ),
    ]
